service:
  name: name-resolver
# app and org for use with dashboard.serverless.com
  app: api
  org: idealwebsolutions

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: {
      forceInclude: ['pg', 'knex']
    }

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}

functions:
  queryAll:
    handler: src/handler.queryAll
    events:
      - http:
          method: get
          path: /
          requests:
            parameters:
              querystrings:
                query: true
                params: false
                redirect: false
          cors: true
